3rd task function(LimitSizeStream)
js-tasks-ru/nodejs-20210513_andrey859 pull request #3
Opened 2021-08-08 11:53 UTC by fornax-eve

2021-08-08 11:54 UTC, jsru commented
Добавляю преподавателя (@RidgeA) для код-ревью.

2021-08-10 08:14 UTC, RidgeA requested changes

2021-08-10 08:14 UTC, RidgeA commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +  #limit = 1056;
Почему именно такой лимит "по умолчанию" ?

2021-08-10 08:14 UTC, RidgeA commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +  #encoding = 'utf8';
похоже, что `encoding` не используется (и не должно)

2021-08-10 08:14 UTC, RidgeA commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +        throw new LimitExceededError();
Нет необходимости выбрасывать ошибку и потом ее сразу отлавливать, можно сразу сделать `callback(new LimitExceededError());`

2021-08-11 08:34 UTC, fornax-eve commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +        throw new LimitExceededError();
Это в блоке else прописывать? Или это уже использовать не try - catch?

2021-08-11 08:38 UTC, fornax-eve commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +  #limit = 1056;
исправил на #limit;

2021-08-11 11:29 UTC, fornax-eve commented
Я вчера закинул сюда ещё вторую задачу с этой темы. Но похоже она не проходила автоматическое тестирование. Но она есть внизу там где Merged

2021-08-11 11:49 UTC, RidgeA commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +        throw new LimitExceededError();
Да, верно. И try/catch/finally уже не нужен получается

2021-08-11 11:53 UTC, RidgeA commented
@fornax-eve оно все попало в один пулл-реквест. 
Поправьте код с try/catch/finally и я аппрувну - после этого должно смержится

2021-08-15 08:31 UTC, fornax-eve commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +        throw new LimitExceededError();
Оно почему-то выбрасывает вот такую ошибку, если прописываю callback в else
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

2021-08-16 07:52 UTC, RidgeA commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +        throw new LimitExceededError();
Залейте пожалуйста код, я посмотрю

2021-08-17 20:22 UTC, jsru commented
Добавляю преподавателя (@RidgeA) для код-ревью.

2021-08-17 20:30 UTC, fornax-eve commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +        throw new LimitExceededError();
Получилось. Небыло коллбэка в if..
Залил.

2021-08-18 07:34 UTC, RidgeA approved these changes

2021-08-18 07:34 UTC, merged